### ISSUE TITLE
[Domino Visual Editor] Shared Action Support

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#1014]
We would like to add support for Shared Actions in the Form editor (and the View editor, once this is available).

**Comment by JoelProminic** [comment]
Here is a design that is intended to use shared actions only:
![image](https://user-images.githubusercontent.com/24532731/205185197-58e47757-11b5-4e57-96b7-e7a26a80938d.png)
![image](https://user-images.githubusercontent.com/24532731/205185224-faa656a4-5f01-4924-8d4c-2495c57f5797.png)

This is a bit complicated, so we can discuss it more tomorrow if needed.  Hopefully it should give some clarification about what we discussed today.

I'm tagging @JustinProminic in case he has any early thoughts on this.

**Comment by JoelProminic** [comment]
@feather812002, please work in a branch for this - it looks like it will be more complicated than I originally though.

**Comment by JoelProminic** [comment]
We briefly discussed the syntax highlighting for the @Formula editor today.  It looks like syntax highlighting is configured in files like these:
https://github.com/Moonshine-IDE/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/syntax/XMLSyntaxPlugin.as
https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/blob/master/src/moonshine/editor/text/syntax/parser/XMLLineParser.hx
https://github.com/Moonshine-IDE/moonshine-feathersui-text-editor/blob/master/src/moonshine/editor/text/syntax/format/XMLSyntaxFormatBuilder.hx

This doesn't look to bad, so we can revisit this in a later iteration.

**Comment by JoelProminic** [comment]
The MoonshineWeb build is currently failing in Bamboo with this error:

    28-Dec-2022 10:48:48 	CompileWeb:
    28-Dec-2022 10:48:48 	     [copy] Copying 6758 files to -snip-/Moonshine-IDE/ide/MoonshineWEBevolved/build/bin-debug/elements
    28-Dec-2022 10:48:52 	     [echo] /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1
    28-Dec-2022 10:48:52 	     [echo] ../../MoonshineSharedCore
    28-Dec-2022 10:48:52 	     [echo] ../../MoonshineSharedCore/src/locale/{locale}
    28-Dec-2022 10:48:52 	     [echo] ../src
    28-Dec-2022 10:48:53 	    [mxmlc] Loading configuration file /Users/mmb/SDKs/Flex_4.16.1_AIR_33.1/frameworks/flex-config.xml
    28-Dec-2022 10:49:05 	    [mxmlc] -snip-/Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/ui/editor/DominoFormulaEditor.as(67): col: 42 Error: Type was not found or was not a compile-time constant: DominoActionVisualEditorView.
    28-Dec-2022 10:49:05 	    [mxmlc] 
    28-Dec-2022 10:49:05 	    [mxmlc]                 public function get dominoActionView():DominoActionVisualEditorView
    28-Dec-2022 10:49:05 	    [mxmlc]                                                        ^
    28-Dec-2022 10:49:05 	    [mxmlc] 


I can still get a MoonshineDesktop build for testing, but this needs to be fixed before a merge.

**Comment by JoelProminic** [comment]
Some notes from today's discussion:

![image](https://user-images.githubusercontent.com/24532731/209867330-cf339adb-35da-4dea-85d7-46d245db50e8.png)

- I feel we should not allow the user to change the path for the action.  We can display the path as a label or disabled field with the label "Shared actions will be stored at this path:"
- The Other Actions list was not updated after an action was created.  It updated when the form was reopened, though.
- When creating another action, the  Source Folder was blank, and each key press triggered an error like this:

```
: Error #1009
: TypeError: Error #1009
: 	at components.popup.newFile::NewFileBase/onNameChanged()
: 	at components.popup.newFile::NewDominoActionPopup/onNameChanged()
: 	at components.popup.newFile::NewDominoActionPopup/__txtFileName_change()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at spark.components.supportClasses::SkinnableTextBase/textDisplay_changeHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at spark.components::RichEditableText/textContainerManager_flowOperationCompleteHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at flashx.textLayout.container::TextContainerManager/dispatchEvent()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at flashx.textLayout.elements::TextFlow/dispatchEvent()
: 	at flashx.textLayout.edit::EditManager/finalizeDo()
: 	at flashx.textLayout.edit::EditManager/doOperation()
: 	at flashx.textLayout.edit::EditManager/flushPendingOperations()
: 	at flashx.textLayout.edit::SelectionManager/enterFrameHandler()
:
: Click here to Report a Bug

```

![image](https://user-images.githubusercontent.com/24532731/209867097-b94f343b-c27d-4f86-a2e1-4d7ab33b2e54.png)

- The header and Title field should expand to fit the width of the sidebar.
- "Acrion" should be "Action"
- "showinmenu" should be "Show in menu" (for the UI)
- "showinbar" should be "Show in bar" (for the UI)
- "ID" should be hidden and computed based on the actions currently in the Shared Action file.
- The default "Title" should be the Action Name from the Create prompt

**Comment by JoelProminic** [comment]
Issue from last week | Status
-- | --
Bamboo Web Build | Fixed
Prompt error after creating second action | Could not reproduce
Don't allow user to change Action path + label update | Confirmed.  Path can be selected for copy
Other Actions list was not updated | Fixed
Expand header and Title field on sidebar resize | Header is updated, Title is not (but this may be removed - see below)
"Acrion" to "Action" | Confirmed
Update labels to "Show in menu" and "Show in bar" | Confirmed
"ID" should be hidden and computed | Confirmed
"Title" should default to the file name | Confirmed.  More thoughts will be added for this below

While testing today, I somehow got to a case where no files were selected in the sidebar.   In this case, I got this message:

> Please select which project that you want to creat the new Action at first

![image](https://user-images.githubusercontent.com/24532731/210396964-edf82fa1-8b45-40ae-8ad2-a947bcd6790c.png)

This message makes sense when the action is created from the menu (File > New > Domino Visual Editor Action), but the text should be updated 

> Please select the project where the shared action should be created.

However, when an action is created from a form, we need to make sure that the action is created in the same project as the form, rather than in the selected project.

**Comment by JoelProminic** [comment]
Some discussion from last week:

>**Bing:**
>09:47:27: OKay, I test it , it look like work find , just one question  ,as your require the default title will same with the action file name
>But if we change the title name , do we should rename the action file name again ?
>Or the title name keep different with the file name ? 
>**Joel:**
>09:52:33: I was thinking that this was an independent label, but I can see that updating the action name in Domino Designer also renames the shared action in the tree. 
>**Bing:**
>09:53:48: Yes, the title name maybe more complex , I think keep it independet label with the file name more better 
>09:54:11: Yes, the shared action tree list the file name , rather than the title name  
>**Joel:**
>10:00:10: Since these files are not the final storage from the actions, we have some flexibility for this:
>1. Get rid of the Action name in this sidebar and rename the file only
>2. Rename the file when the action name is updated (and vice versa)
>3. Keep the action name property independent.   However, the file name could get out of sync in this case.
>
>I'm thinking 3 will cause trouble later, and 1 seems easier than 2.

So, I would like to get rid of Title or change it to label instead.  We will change the action name by renaming the file (note that this may require additional logic to update the `Shared Actions` file and Forms/Views/Pages (unless these use the IDs only).

**Comment by feather812002** [comment]
> 

I work on this rename issue , I found it more complex , 
for example, if we create a new action , and insert it into form .after we rename it , do we need rename it from other form /view?

If the action exist other form or view is ID reference , we don't need worry this ,but if it is exist as the title name , it will be crash some action after the rename.

Let us put this aside and work into build the action back into NSF database

**Comment by JoelProminic** [comment]
@feather812002 found that the exported forms in NSFConverterPortalProject had the Actions configured with binary data, encoded in Base64 format.  We haven't figured out how to decode the binary data, so we we are moving on to other tasks for now.  We can still use the Shared Actions in the mockup editor.

**Comment by JoelProminic** [comment]
While testing #1189, I got an error when building the project

    : [INFO] java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception while importing element Code/actions/Shared Actions
    ...
    : [INFO] Caused by: java.lang.RuntimeException: Exception while importing element Code/actions/Shared Actions
    ...
    : [INFO] Caused by: java.lang.NullPointerException
    : [INFO] 	at org.openntf.nsfodp.compiler.ODPCompiler.importDxl(ODPCompiler.java:917)
    : [INFO] 	at org.openntf.nsfodp.compiler.ODPCompiler.lambda$9(ODPCompiler.java:616)
    : [INFO] 	... 33 more
    : [INFO] An error has occurred. See the log file
    : [INFO] /tmp/nsfodp/20230306174741/nsfs/nsf-moonshine/target/nsfodpequinox/configuration/nsfodp.log.


Unfortunately, I didn't save the failing file.  I'm not sure why this file was even created/changed, since I only did tests against Forms and Pages

I tried to reproduce this with a fresh project, but it didn't trigger again for me.

I know that this task is on hold for now, but I want to make sure this code is in a state where it won't break Domino Visual Editor when we merge `features/issue-1082_IMOS_Convert` to master for #1189.

**Comment by JoelProminic** [comment]
SharedAction should be removed from the component sidebar, since we are not adding actions like this with the updated design.

**Comment by JoelProminic** [comment]
@feather812002, do you remember where you were seeing the binary data for actions? Looking at the DTD, I see that [`<action>`](https://help.hcltechsw.com/dom_designer/11.0.1/basic/H_ACTION_ELEMENT_XML_.html) is supposed to contain [`<code>`](https://help.hcltechsw.com/dom_designer/11.0.1/basic/H_CODE_ELEMENT_XML.html), which should contain plain-text code in one of the supporting languages.  I exported some shared actions from Domino Designer (normal format), and I didn't see the binary data.

**Comment by JoelProminic** [comment]
I would like to get an example of this format attached/linked to this issue so that we can investigate it further.

I tried to generate this in note format using [nsf-to-odp-exporter](https://github.com/Moonshine-IDE/NSFConverterPortalProject/tree/main/nsf-to-odp-exporter), but I saw the actions and shared actions were missing.  Was this disabled as part of the branch cleanup above?

I don't see "Shared Actions" in the [nsfodp examples](https://github.com/OpenNTF/org.openntf.nsfodp/tree/develop/examples).  I do see an example in the [On Disk Project template](https://github.com/Moonshine-IDE/Moonshine-IDE/blob/357045c2ac2e8dd8fd7de7162ed32076c5e62995/ide/MoonshineSharedCore/src/elements/templates/projects/On%20Disk%20Project/nsfs/nsf-moonshine/odp/Code/actions/Shared%20Actions), but I don't know how this was generated.
