### ISSUE TITLE
BadLocationException for Java Gradle Projects

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Moonshine-IDE#579]
@joshtynjala , I have been seeing errors like this from the language server when testing with Java Gradle projects.  Sometimes I am seeing these on project open - for examples:

    : org.eclipse.jface.text.BadLocationException
    : 	at org.eclipse.jface.text.ListLineTracker.getLineOffset(ListLineTracker.java:197)
    : 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:160)
    : 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:876)
    : 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:320)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.convertRange(WorkspaceDiagnosticsHandler.java:335)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnostic(WorkspaceDiagnosticsHandler.java:315)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.lambda$3(WorkspaceDiagnosticsHandler.java:300)
    : 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    : 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
    : 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    : 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    : 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    : 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    : 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnosticsArray(WorkspaceDiagnosticsHandler.java:302)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.visit(WorkspaceDiagnosticsHandler.java:151)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
    : 	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.resourceChanged(WorkspaceDiagnosticsHandler.java:84)
    : 	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
    : 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
    : 	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
    : 	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
    : 	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
    : 	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2308)
    : 	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
    : 	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
    : 	at org.eclipse.buildship.core.internal.operation.ToolingApiJob.run(ToolingApiJob.java:64)
    : 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

I saw a similar error with Edit > Rename Symbol:

    : org.eclipse.jface.text.BadLocationException
    : 	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
    : 	at org.eclipse.jface.text.TreeLineTracker.offsetByLine(TreeLineTracker.java:335)
    : 	at org.eclipse.jface.text.TreeLineTracker.getLineOffset(TreeLineTracker.java:1111)
    : 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:160)
    : 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:876)
    : 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:323)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:56)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:41)
    : 	at org.eclipse.jdt.ls.core.internal.corrections.DiagnosticsHelper.getStartOffset(DiagnosticsHelper.java:51)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:79)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:590)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$28(JDTLanguageServer.java:807)
    : 	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
    : 	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
    : 	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
    : 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    : 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    : 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    : 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    : Jun 10, 2019 5:43:11 PM 

I can consistently trigger an error like these when CMD-clicking on the Person reference in TestJavaGradleReference.java in this project:
[2019_06_10__TestJavaGradleReference.zip](https://github.com/prominic/Moonshine-IDE/files/3274066/2019_06_10__TestJavaGradleReference.zip)

Do you have any insight for this?  

JFace is a UI framework, so I'm wondering if the Eclipse language server is trying to interact with some UI component.

**Comment by joshtynjala** [comment]
I can reproduce this error when opening a Java Gradle project. Not sure what's causing it, though. It seems that the language server is creating a compiler error/problem, but it's failing because it can't properly figure out the line number.

I see that my project reports this problem in build.gradle:

> Could not create an instance of Tooling API implementation using the specified Gradle installation 'C:\ProgramData\chocolatey\lib\gradle\tools\gradle-5.5'.
Failed to load native library 'native-platform.dll' for Windows 10 amd64.
The system cannot find the path specified

This might be a bug in the Java language server. The error is associated with the build.gradle file, but maybe that part of the language server is expecting Java files only.

**Comment by joshtynjala** [comment]
I can no longer reproduce this issue. Closing.

**Comment by JoelProminic** [comment]
I don't remember seeing this error recently.  I'll reopen this if I see the error again.

**Comment by JoelProminic** [comment]
@joshtynjala, I'm seeing lots of errors like above for [this project](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD).


    : Nov 10, 2022, 3:15:37 PM BadLocationException
    : null
    : org.eclipse.jface.text.BadLocationException
    : 	at org.eclipse.jface.text.ListLineTracker.getLineOffset(ListLineTracker.java:197)
    : 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:161)
    : 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:877)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:85)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:69)
    : 	at org.eclipse.jdt.ls.core.internal.corrections.DiagnosticsHelper.getEndOffset(DiagnosticsHelper.java:38)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getContext(CodeActionHandler.java:346)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:134)
    : 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$15(JDTLanguageServer.java:676)
    : 	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
    : 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
    : 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    : 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    : 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    : 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    : 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    : 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Currently this is triggering repeatedly while editing a file.  For example, I tried to create a new subclass of [LogInterface](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD/blob/main/src/main/java/com/moonshine/domino/log/LogInterface.java) and I got an error every time I added a method from LogInterface.

OS: macOS Catalina 10.15.7
MoonshineDevelopment:  3.3.4 Build 2888
Java:  "17.0.5" 2022-10-18

**Comment by joshtynjala** [comment]
> I'm seeing lots of errors like above for [this project](https://github.com/Moonshine-IDE/Moonshine-Domino-CRUD).

Unfortunately, I can't seem to open the linked project in Moonshine. The language server exits unexpectedly. After git cloning the project, I manually added lib/Notes.jar, which I got from here: https://github.com/DominoIDP/domino_idp/blob/master/dist/Notes.jar. That doesn't seem to be enough to make it happy, though.

Interestingly, Cmd+B to build seems to work successfully.

**Comment by JoelProminic** [comment]
I noticed a similar issue earlier today, but the language server started working after some work.  I think I tried the following, but I don't remember exactly which one fixed it:
- Reopen the project
- Manually run `gradle clean eclipse`
- Open another Java Gradle project.

I had assumed that this problem was caused by some earlier testing, but I'll watch for it to happen again.

I restarted Moonshine again after my last comment, and it is working fine for now.   I have seen the BadLocationException before for this project, though, so I think it will trigger again before too long.
