### ISSUE TITLE
Create getter/setter problems

### ISSUE THREAD

**Issue by Aszusz** [Moonshine-IDE/Moonshine-IDE#895]
Create a Java project and take a look at the helper tooltip for a private field:
 
![Screenshot 2021-10-04 at 18 15 23](https://user-images.githubusercontent.com/7197014/135887372-55a2505f-faa7-4050-8a29-b388037ee104.png)

It has two entries for creating getters/setters. What is the intended difference between them?

- Clicking on `Generate Getters and Setters` does nothing
- Clicking `create getter and setter for fieldName` throws an error, but the methods are created correctly:
```
: Oct 4, 2021, 6:12:34 PM 
: null
: org.eclipse.jface.text.BadLocationException
: 	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
: 	at org.eclipse.jface.text.TreeLineTracker.offsetByLine(TreeLineTracker.java:335)
: 	at org.eclipse.jface.text.TreeLineTracker.getLineOffset(TreeLineTracker.java:1111)
: 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:161)
: 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:877)
: 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:323)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:85)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:69)
: 	at org.eclipse.jdt.ls.core.internal.corrections.DiagnosticsHelper.getStartOffset(DiagnosticsHelper.java:53)
: 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:94)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:640)
: 	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
: Oct 4, 2021, 6:12:34 PM 
: null
: org.eclipse.jface.text.BadLocationException
: 	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
: 	at org.eclipse.jface.text.TreeLineTracker.offsetByLine(TreeLineTracker.java:335)
: 	at org.eclipse.jface.text.TreeLineTracker.getLineOffset(TreeLineTracker.java:1111)
: 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:161)
: 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:877)
: 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:323)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:85)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:69)
: 	at org.eclipse.jdt.ls.core.internal.corrections.DiagnosticsHelper.getEndOffset(DiagnosticsHelper.java:38)
: 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:95)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:640)
: 	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
: Oct 4, 2021, 6:12:34 PM 
: null
: org.eclipse.jface.text.BadLocationException
: 	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
: 	at org.eclipse.jface.text.TreeLineTracker.offsetByLine(TreeLineTracker.java:335)
: 	at org.eclipse.jface.text.TreeLineTracker.getLineOffset(TreeLineTracker.java:1111)
: 	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:161)
: 	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:877)
: 	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.getLineOffset(SynchronizableDocument.java:323)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:85)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JsonRpcHelpers.toOffset(JsonRpcHelpers.java:69)
: 	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:717)
: 	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementAtSelection(JDTUtils.java:706)
: 	at org.eclipse.jdt.ls.core.internal.text.correction.SourceAssistProcessor.getSourceActionCommands(SourceAssistProcessor.java:104)
: 	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:175)
: 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$14(JDTLanguageServer.java:640)
: 	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by rat-moonshine** [comment]
I have added @joshtynjala to look into this once.

**Comment by joshtynjala** [comment]
> What is the intended difference between them?

You would need to ask the developers who created the Java language server. We didn't create it. We're just using it.

If I had to guess, "Generate Getters and Setters" might create getters and setters for all private variables? Just a guess.

> Clicking create getter and setter for fieldName throws an error, but the methods are created correctly:

Hopefully, the next time that I upgrade the Java language server to a new version, this error will go away. It may have been a temporary bug in the particular version we are using currently.
